Tracker:AddLocations("locations/Ancient Era.json")
Tracker:AddLocations("locations/Atomic Era.json")
Tracker:AddLocations("locations/Classical Era.json")
Tracker:AddLocations("locations/Future Era.json")
Tracker:AddLocations("locations/Industrial Era.json")
Tracker:AddLocations("locations/Information Era.json")
Tracker:AddLocations("locations/Medieval Era.json")
Tracker:AddLocations("locations/Modern Era.json")
Tracker:AddLocations("locations/Renaissance Era.json")
Tracker:AddLocations("locations/Overworld.json")
